-- ===========================================================================
-- Sprint 022 — Client Accounting Identity + VW Merge
-- Generated by scripts/import_client_accounting.py — do not hand-edit.
-- Operator decisions: 2026-08-10 Tatiana: full customer mapping confirmed; VW and Volkswagen collapse to one client named VW on C0208; Volvo MS shares Volvo's C0099.
--
-- Safe to re-run. Every statement is idempotent and the whole file is one
-- transaction: if any guard fails, NOTHING is applied.
--
-- Touches the `clients` table only. No schema change. No estimate value
-- changes. fee_types and rate_card_items are never written.
-- ===========================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- GUARD 1 — refuse to proceed unless the two VW records look as audited.
--
-- rate_card_items.client_id is ON DELETE CASCADE, so deleting the wrong
-- record destroys its rate card silently. This guard is the only thing
-- standing between a mistake and 70 lost prices. Do not remove it.
-- ---------------------------------------------------------------------
DO $$
DECLARE
  vw_rows   INT;
  vk_rows   INT;
  vw_count  INT;
  vk_count  INT;
BEGIN
  SELECT count(*) INTO vw_count FROM clients WHERE lower(name) = 'vw';
  SELECT count(*) INTO vk_count FROM clients WHERE lower(name) = 'volkswagen';

  IF vw_count = 1 AND vk_count = 1 THEN
    SELECT count(*) INTO vw_rows FROM rate_card_items r
      JOIN clients c ON c.id = r.client_id WHERE lower(c.name) = 'vw';
    SELECT count(*) INTO vk_rows FROM rate_card_items r
      JOIN clients c ON c.id = r.client_id WHERE lower(c.name) = 'volkswagen';

    IF vw_rows <> 0 THEN
      RAISE EXCEPTION 'ABORT: the VW record holds % rate card rows (expected 0). Deleting it would destroy them. Re-run the Stage A audit and re-plan.', vw_rows;
    END IF;

    IF vk_rows = 0 THEN
      RAISE EXCEPTION 'ABORT: the Volkswagen record holds 0 rate card rows (expected %). The wrong record would survive the merge.', 70;
    END IF;

  ELSIF vw_count = 1 AND vk_count = 0 THEN
    RAISE NOTICE 'Merge already applied (VW exists, Volkswagen does not). Skipping merge, applying customer IDs only.';
  ELSE
    RAISE EXCEPTION 'ABORT: unexpected client state — % row(s) named VW, % named Volkswagen.', vw_count, vk_count;
  END IF;
END $$;

-- ---------------------------------------------------------------------
-- MERGE — order is mandatory.
--   1. carry VW's non-standard office payout onto Volkswagen
--   2. delete the empty VW row (frees the UNIQUE name AND code)
--   3. rename Volkswagen to VW and give it the code + customer ID
-- Renaming before deleting collides on clients.name / clients.code.
-- ---------------------------------------------------------------------

-- 1. Carry the payout across. Read live rather than hardcoded, so the
--    real value moves even if it changed since the audit. Only fires when
--    both rows still exist, which makes this safe to re-run.
UPDATE clients SET office_payout_pct = (
         SELECT office_payout_pct FROM clients WHERE lower(name) = 'vw'
       )
 WHERE lower(name) = 'volkswagen'
   AND EXISTS (SELECT 1 FROM clients WHERE lower(name) = 'vw');

-- 2. Delete the empty VW record. Guard 1 has proven it holds no rates.
DELETE FROM clients
 WHERE lower(name) = 'vw'
   AND NOT EXISTS (
         SELECT 1 FROM rate_card_items r
          JOIN clients c ON c.id = r.client_id
         WHERE lower(c.name) = 'vw'
       );

-- 3. Rename Volkswagen and take over the identity.
UPDATE clients
   SET name = 'VW',
       code = 'VW',
       intacct_customer_id = 'C0208'
 WHERE lower(name) = 'volkswagen';

-- ---------------------------------------------------------------------
-- CUSTOMER IDS — 20 guarded updates, keyed on name.
-- `No Client` is deliberately absent and stays NULL.
-- ---------------------------------------------------------------------
UPDATE clients SET intacct_customer_id = 'C0004' WHERE lower(name) = lower('Acura');
UPDATE clients SET intacct_customer_id = 'C0009' WHERE lower(name) = lower('Audi');
UPDATE clients SET intacct_customer_id = 'C0091' WHERE lower(name) = lower('Bentley');
UPDATE clients SET intacct_customer_id = 'C0202' WHERE lower(name) = lower('Ferrari');
UPDATE clients SET intacct_customer_id = 'C0121' WHERE lower(name) = lower('Genesis');
UPDATE clients SET intacct_customer_id = 'C0255' WHERE lower(name) = lower('Hankook');
UPDATE clients SET intacct_customer_id = 'C0004' WHERE lower(name) = lower('Honda');
UPDATE clients SET intacct_customer_id = 'C0019' WHERE lower(name) = lower('Hyundai');
UPDATE clients SET intacct_customer_id = 'C0026' WHERE lower(name) = lower('JLR');
UPDATE clients SET intacct_customer_id = 'C0156' WHERE lower(name) = lower('Lamborghini');
UPDATE clients SET intacct_customer_id = 'C0134' WHERE lower(name) = lower('Lexus');
UPDATE clients SET intacct_customer_id = 'C0294' WHERE lower(name) = lower('Lucid');
UPDATE clients SET intacct_customer_id = 'C0032' WHERE lower(name) = lower('MB');
UPDATE clients SET intacct_customer_id = 'C0028' WHERE lower(name) = lower('Maserati');
UPDATE clients SET intacct_customer_id = 'C0029' WHERE lower(name) = lower('Mazda');
UPDATE clients SET intacct_customer_id = 'C0207' WHERE lower(name) = lower('Polestar');
UPDATE clients SET intacct_customer_id = 'C0041' WHERE lower(name) = lower('Porsche');
UPDATE clients SET intacct_customer_id = 'C0048' WHERE lower(name) = lower('Toyota');
UPDATE clients SET intacct_customer_id = 'C0099' WHERE lower(name) = lower('Volvo');
UPDATE clients SET intacct_customer_id = 'C0099' WHERE lower(name) = lower('Volvo MS');

-- ---------------------------------------------------------------------
-- GUARD 2 — verify the result before COMMIT. Any failure rolls back the
-- entire file, leaving the database exactly as it was.
-- ---------------------------------------------------------------------
DO $$
DECLARE
  vw_n      INT;
  vk_n      INT;
  vw_rates  INT;
  vw_payout NUMERIC;
  with_id   INT;
BEGIN
  SELECT count(*) INTO vw_n FROM clients WHERE name = 'VW';
  SELECT count(*) INTO vk_n FROM clients WHERE lower(name) = 'volkswagen';
  IF vw_n <> 1 OR vk_n <> 0 THEN
    RAISE EXCEPTION 'ABORT: after merge expected exactly 1 VW and 0 Volkswagen, found % and %.', vw_n, vk_n;
  END IF;

  SELECT count(*) INTO vw_rates FROM rate_card_items r
    JOIN clients c ON c.id = r.client_id WHERE c.name = 'VW';
  IF vw_rates <> 70 THEN
    RAISE EXCEPTION 'ABORT: merged VW holds % rate card rows (expected %). The wrong record survived.', vw_rates, 70;
  END IF;

  SELECT office_payout_pct INTO vw_payout FROM clients WHERE name = 'VW';
  IF vw_payout <> 0.8000 THEN
    RAISE EXCEPTION 'ABORT: merged VW office_payout_pct is % (expected %). The non-standard payout was lost; every future VW estimate would be mispriced.', vw_payout, 0.8000;
  END IF;

  SELECT count(*) INTO with_id FROM clients WHERE intacct_customer_id IS NOT NULL;
  IF with_id <> 21 THEN
    RAISE EXCEPTION 'ABORT: % clients carry a customer ID (expected %). A client name in the mapping probably does not match the database.', with_id, 21;
  END IF;

  RAISE NOTICE 'OK — 1 VW with % rates at payout %, % clients carry a customer ID.', vw_rates, vw_payout, with_id;
END $$;

COMMIT;
