-- ===========================================================================
-- Sprint 026 — Corporate cost on rate card items
-- Generated by scripts/import_corporate_costs.py — do not hand-edit.
-- 2026-08-10 Ray: confirmed 50% corporate cost, build it.
--
-- Rule recovered from the Sprint 016 cost rate card (scripts/import_rate_cards.sql,
-- still in git): corporate cost was 50% of the unit rate across every section;
-- pass-throughs sat at 100% (cost == rate).
--
-- Stored as a PERCENT so a later rate change carries the cost with it.
-- office_cost is deliberately left NULL: office cost is derived from the
-- client's office_payout_pct at estimate time, and a stored copy would drift.
--
-- Safe to re-run. One transaction; if a guard fails, NOTHING is applied.
-- Touches rate_card_items.corporate_cost / corporate_cost_is_percent only.
-- ===========================================================================

BEGIN;

-- Pass-through items: DriveShop's cost is the full rate.
UPDATE rate_card_items
   SET corporate_cost = 100,
       corporate_cost_is_percent = true
 WHERE is_pass_through = true;

-- Everything else: half the rate.
UPDATE rate_card_items
   SET corporate_cost = 50,
       corporate_cost_is_percent = true
 WHERE is_pass_through = false;

-- ---------------------------------------------------------------------
-- GUARD — verify before COMMIT.
-- ---------------------------------------------------------------------
DO $$
DECLARE total INT; pt INT; std INT; office_touched INT;
BEGIN
  SELECT count(*) INTO total FROM rate_card_items WHERE corporate_cost IS NOT NULL;
  SELECT count(*) INTO pt  FROM rate_card_items WHERE is_pass_through = true  AND corporate_cost = 100;
  SELECT count(*) INTO std FROM rate_card_items WHERE is_pass_through = false AND corporate_cost = 50;
  SELECT count(*) INTO office_touched FROM rate_card_items WHERE office_cost IS NOT NULL;

  IF total <> 1466 THEN
    RAISE EXCEPTION 'ABORT: % rows carry a corporate cost (expected %). Rate card row count has changed since planning.', total, 1466;
  END IF;
  IF pt <> 945 THEN
    RAISE EXCEPTION 'ABORT: % pass-through rows at 100%% (expected %).', pt, 945;
  END IF;
  IF std <> 521 THEN
    RAISE EXCEPTION 'ABORT: % standard rows at 50%% (expected %).', std, 521;
  END IF;
  IF office_touched <> 0 THEN
    RAISE EXCEPTION 'ABORT: % rows have a stored office_cost. Office cost must stay derived from the client payout, not stored.', office_touched;
  END IF;

  RAISE NOTICE 'OK — % rows costed (% pass-through at 100%%, % standard at 50%%); office_cost untouched.', total, pt, std;
END $$;

COMMIT;
