#!/usr/bin/env python3
"""
Sprint 023 — Client AR payment terms.

Sets clients.default_payment_terms from the list Tatiana supplied.

Usage:
    python scripts/import_client_payment_terms.py            # dry-run, prints only
    python scripts/import_client_payment_terms.py --confirm  # also writes the .sql

An OPERATOR then applies scripts/import_client_payment_terms.sql via the
Supabase SQL editor. This script NEVER writes to the database.

Provenance:
    Tatiana, `Customers with Pmt Terms.xlsx` (298 customers, `Term` column),
    2026-08-10, joined on the Intacct customer IDs loaded in Sprint 022. Every
    one of our 21 mapped customers has a term; none came back blank. The values
    are transcribed literally below rather than parsed at runtime, so the script
    has no spreadsheet dependency and the exact values are reviewable in the
    diff. Do not re-derive them.

Why this matters:
    The exporter treats AR payment terms as a hard requirement with NO fallback
    (src/lib/accounting-export-line-service.ts:644) — unlike AP, which can fall
    back to the office profile. A null here blocks every invoice for that client.

Note on format:
    These are free-text labels ("Net 30"), exactly as Intacct reports them. If a
    real export turns out to need a term ID rather than the label, that is a
    Sprint 025 finding — do not guess at a code here.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_SQL_PATH = PROJECT_ROOT / "scripts" / "import_client_payment_terms.sql"

SOURCE = "Tatiana, 'Customers with Pmt Terms.xlsx', 2026-08-10"

# Client name -> AR payment term. `No Client` is deliberately absent: it is our
# internal fallback, not a DriveShop account, and stays NULL.
PAYMENT_TERMS: dict[str, str] = {
    "Acura":       "Net 30",
    "Audi":        "Net 60",
    "Bentley":     "Net 60",
    "Ferrari":     "Net 30",
    "Genesis":     "Net 30",
    "Hankook":     "Net 30",
    "Honda":       "Net 30",
    "Hyundai":     "Net 30",
    "JLR":         "Net 30",
    "Lamborghini": "Net 60",
    "Lexus":       "Net 45",
    "Lucid":       "Net 45",
    "Maserati":    "Net 60",
    "Mazda":       "Net 30",   # already set; update is a no-op
    "MB":          "Net 30",
    "Polestar":    "Net 45",
    "Porsche":     "Net 30",
    "Toyota":      "Net 45",
    "Volvo":       "Net 45",
    "Volvo MS":    "Net 45",
    "VW":          "Net 60",
}

EXPECTED_CLIENTS_WITH_TERMS = 21


def sql_str(s: str) -> str:
    return "'" + str(s).replace("'", "''") + "'"


def generate_sql() -> str:
    lines: list[str] = []
    add = lines.append

    add("-- " + "=" * 75)
    add("-- Sprint 023 — Client AR payment terms")
    add("-- Generated by scripts/import_client_payment_terms.py — do not hand-edit.")
    add(f"-- Source: {SOURCE}")
    add("--")
    add("-- Safe to re-run. One transaction: if the guard fails, NOTHING is applied.")
    add("-- Touches the `clients` table only. No schema change.")
    add("-- " + "=" * 75)
    add("")
    add("BEGIN;")
    add("")
    add(f"-- {len(PAYMENT_TERMS)} guarded updates, keyed on name.")
    add("-- `No Client` is deliberately absent and stays NULL.")
    for name in sorted(PAYMENT_TERMS):
        term = PAYMENT_TERMS[name]
        add(
            f"UPDATE clients SET default_payment_terms = {sql_str(term)} "
            f"WHERE lower(name) = lower({sql_str(name)});"
        )
    add("")
    add("-- ---------------------------------------------------------------------")
    add("-- GUARD — verify before COMMIT. A client name that does not match the")
    add("-- database would leave its UPDATE affecting zero rows, silently. This is")
    add("-- the only realistic failure mode for a guarded update keyed on name.")
    add("-- ---------------------------------------------------------------------")
    add("DO $$")
    add("DECLARE n INT;")
    add("BEGIN")
    add("  SELECT count(*) INTO n FROM clients WHERE default_payment_terms IS NOT NULL;")
    add(f"  IF n <> {EXPECTED_CLIENTS_WITH_TERMS} THEN")
    add("    RAISE EXCEPTION 'ABORT: % clients carry payment terms (expected %). "
        "A client name in the mapping probably does not match the database.', "
        f"n, {EXPECTED_CLIENTS_WITH_TERMS};")
    add("  END IF;")
    add("  RAISE NOTICE 'OK — % clients carry AR payment terms.', n;")
    add("END $$;")
    add("")
    add("COMMIT;")
    add("")
    return "\n".join(lines)


def print_summary() -> None:
    by_term: dict[str, list[str]] = {}
    for name, term in PAYMENT_TERMS.items():
        by_term.setdefault(term, []).append(name)

    print("\nSprint 023 — Client AR payment terms (DRY RUN)")
    print("=" * 62)
    print(f"\nSource: {SOURCE}")
    print(f"\nClients to update: {len(PAYMENT_TERMS)}")
    for term in sorted(by_term):
        names = ", ".join(sorted(by_term[term]))
        print(f"  {term:<8} ({len(by_term[term])})  {names}")
    print("  (none)   No Client — internal fallback, deliberately left NULL")
    print(f"\nGuard: aborts unless exactly {EXPECTED_CLIENTS_WITH_TERMS} clients "
          "carry a term after the load.")
    print("This script never connects to the database. An operator applies the SQL.")


def main() -> int:
    parser = argparse.ArgumentParser(description="Load client AR payment terms.")
    parser.add_argument("--confirm", action="store_true",
                        help="also write scripts/import_client_payment_terms.sql")
    args = parser.parse_args()

    print_summary()

    if not args.confirm:
        print(f"\nDry-run only. Re-run with --confirm to write "
              f"{OUTPUT_SQL_PATH.relative_to(PROJECT_ROOT)}.")
        return 0

    sql = generate_sql()
    OUTPUT_SQL_PATH.write_text(sql, encoding="utf-8")
    print(f"\nWrote {OUTPUT_SQL_PATH.relative_to(PROJECT_ROOT)} "
          f"({len(sql.splitlines())} lines).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
