#!/usr/bin/env python3
"""
Sprint 024 — Catalog amendments, decided without Dave.

Dave did not reply, and waiting was blocking the beta. Ray authorised best-guess
decisions on 2026-08-10. Every call below is reversible and recorded in
planning/DECISIONS.md with its reasoning.

Usage:
    python scripts/import_catalog_amendments.py            # dry-run, prints only
    python scripts/import_catalog_amendments.py --confirm  # also writes the .sql

An OPERATOR applies scripts/import_catalog_amendments.sql via the Supabase SQL
editor. This script NEVER writes to the database.

--------------------------------------------------------------------------
WHAT THIS SCRIPT DOES

1. Volvo MS gets Volvo's rate card (69 rows, copied).
   Tatiana confirmed Volvo MS is a program under Volvo with its own rate table,
   but Dave never sent a Volvo MS tab, so it had zero prices: invoiceable but
   unable to produce an estimate. Volvo is the closest defensible source — same
   Intacct customer (C0099), same 20% trucking markup, same 2.5% third-party
   markup. Seeding from Volvo is reversible; leaving it empty is a dead client.

2. Right Seat Driver - Travel (I0124) gets an $80 overtime rate on Lucid and MB.
   Dave priced the standalone "Travel O/T" item at exactly 80 on both tabs but
   left the parent row's overtime column blank. Sprint 020 declined to invent
   the value. The intent is unambiguous: every other client's Travel overtime
   equals the standalone item. Setting it is lower risk than leaving those two
   clients unable to bill Travel overtime at all.

--------------------------------------------------------------------------
WHAT THIS SCRIPT DELIBERATELY DOES NOT DO

Three of Dave's items require an Intacct **Item ID**, which only DriveShop's
accounting system can issue. A guess here does not produce a wrong price that
somebody notices — it produces a **fake identifier inside their accounting
system**, on real invoices, that reconciles against nothing. That is the one
class of decision where guessing is worse than waiting, so these stay as they
are and are documented instead:

  - **Chauffeur "High Markets" (I0217 duplicate).** Maserati and Volvo each list
    Standard Market and High Markets under one Item ID. Only one could load.
    Impact is limited: Maserati priced both at 100, so nothing is lost there.
    Volvo loses a high-market rate of 100 and bills chauffeur hours at 90.
  - **EV Charging - Flat Rate** and **Per Diem - Flat Rate.** Both already exist
    as pass-through items (I00601, I0090) and continue to bill on receipts at
    the client markup. A flat-rate variant is a new catalog item needing its own
    Item ID and GL.
  - **I00601 is a malformed Item ID** (five digits where all 159 others are
    four). It arrived that way in DriveShop's own catalog file. "Correcting" it
    to I0060 would invent an ID that may already belong to something else.

None of the three blocks the beta. All three are one email from being resolved.

--------------------------------------------------------------------------
NO WORK NEEDED — verified 2026-08-10, recorded so nobody re-opens them

  - The four items Dave flagged "Duplicate???" (I0202, I0203, I0204, I0205)
    appear on ZERO rate cards, because he left them unpriced on all 20 tabs and
    the Sprint 020 loader skips blanks. They are already invisible in the
    estimate builder. Retiring them further would be a no-op.
  - The blank "In event estimate?" column is moot. The estimate builder reads
    each client's rate_card_items, never the full fee_types catalog, so the 77
    items nobody priced already never appear.
  - GL 4000.99 is referenced nowhere in the codebase or any load script.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_SQL_PATH = PROJECT_ROOT / "scripts" / "import_catalog_amendments.sql"

DECIDED_BY = "2026-08-10 Ray: proceed on best-guess, do not wait for Dave."

SOURCE_CLIENT = "Volvo"
TARGET_CLIENT = "Volvo MS"
EXPECTED_VOLVO_ROWS = 69

TRAVEL_OT_ITEM = "I0124"          # Right Seat Driver - Travel
TRAVEL_OT_RATE = 80
TRAVEL_OT_CLIENTS = ["Lucid", "MB"]


def sql_str(s: str) -> str:
    return "'" + str(s).replace("'", "''") + "'"


def generate_sql() -> str:
    lines: list[str] = []
    add = lines.append
    cl = ", ".join(sql_str(c) for c in TRAVEL_OT_CLIENTS)

    add("-- " + "=" * 75)
    add("-- Sprint 024 — Catalog amendments (decided without Dave)")
    add("-- Generated by scripts/import_catalog_amendments.py — do not hand-edit.")
    add(f"-- {DECIDED_BY}")
    add("--")
    add("-- Safe to re-run. One transaction: if a guard fails, NOTHING is applied.")
    add("-- Touches rate_card_items only. No schema change, no fee_types change.")
    add("-- " + "=" * 75)
    add("")
    add("BEGIN;")
    add("")
    add("-- ---------------------------------------------------------------------")
    add(f"-- 1. Seed {TARGET_CLIENT}'s rate card from {SOURCE_CLIENT}.")
    add("--    The NOT EXISTS makes this idempotent: on a re-run the target")
    add("--    already has rows and nothing is inserted, so rates edited later")
    add("--    are never overwritten by a second apply.")
    add("-- ---------------------------------------------------------------------")
    add("INSERT INTO rate_card_items (")
    add("  client_id, section_id, name, unit_rate, unit_label, gl_code,")
    add("  is_pass_through, has_overtime_rate, overtime_rate,")
    add("  notes, fee_type_id, display_order, is_active, is_rate_locked")
    add(")")
    add(f"SELECT (SELECT id FROM clients WHERE lower(name) = lower({sql_str(TARGET_CLIENT)})),")
    add("       r.section_id, r.name, r.unit_rate, r.unit_label, r.gl_code,")
    add("       r.is_pass_through, r.has_overtime_rate, r.overtime_rate,")
    add("       r.notes, r.fee_type_id, r.display_order, r.is_active, r.is_rate_locked")
    add("  FROM rate_card_items r")
    add(f" WHERE r.client_id = (SELECT id FROM clients WHERE lower(name) = lower({sql_str(SOURCE_CLIENT)}))")
    add("   AND NOT EXISTS (")
    add("         SELECT 1 FROM rate_card_items x")
    add(f"          WHERE x.client_id = (SELECT id FROM clients WHERE lower(name) = lower({sql_str(TARGET_CLIENT)}))")
    add("       );")
    add("")
    add("-- ---------------------------------------------------------------------")
    add(f"-- 2. {TRAVEL_OT_ITEM} Right Seat Driver - Travel: set the ${TRAVEL_OT_RATE} overtime rate")
    add(f"--    Dave implied on {' and '.join(TRAVEL_OT_CLIENTS)} but left off the parent row.")
    add("-- ---------------------------------------------------------------------")
    add("UPDATE rate_card_items")
    add("   SET has_overtime_rate = true,")
    add(f"       overtime_rate = {TRAVEL_OT_RATE}")
    add(f" WHERE fee_type_id = (SELECT id FROM fee_types WHERE intacct_ar_item_id = {sql_str(TRAVEL_OT_ITEM)})")
    add(f"   AND client_id IN (SELECT id FROM clients WHERE name IN ({cl}));")
    add("")
    add("-- ---------------------------------------------------------------------")
    add("-- GUARD — verify before COMMIT.")
    add("-- ---------------------------------------------------------------------")
    add("DO $$")
    add("DECLARE ms_rows INT; src_rows INT; ot_rows INT;")
    add("BEGIN")
    add(f"  SELECT count(*) INTO ms_rows FROM rate_card_items r JOIN clients c ON c.id = r.client_id")
    add(f"   WHERE lower(c.name) = lower({sql_str(TARGET_CLIENT)});")
    add(f"  SELECT count(*) INTO src_rows FROM rate_card_items r JOIN clients c ON c.id = r.client_id")
    add(f"   WHERE lower(c.name) = lower({sql_str(SOURCE_CLIENT)});")
    add("")
    add("  IF ms_rows <> src_rows THEN")
    add(f"    RAISE EXCEPTION 'ABORT: {TARGET_CLIENT} has % rate rows but {SOURCE_CLIENT} has % — the copy did not land cleanly.', ms_rows, src_rows;")
    add("  END IF;")
    add("")
    add("  SELECT count(*) INTO ot_rows FROM rate_card_items r")
    add("    JOIN clients c ON c.id = r.client_id")
    add(f"   WHERE r.fee_type_id = (SELECT id FROM fee_types WHERE intacct_ar_item_id = {sql_str(TRAVEL_OT_ITEM)})")
    add(f"     AND c.name IN ({cl})")
    add(f"     AND r.overtime_rate = {TRAVEL_OT_RATE};")
    add(f"  IF ot_rows <> {len(TRAVEL_OT_CLIENTS)} THEN")
    add(f"    RAISE EXCEPTION 'ABORT: expected {len(TRAVEL_OT_CLIENTS)} Travel overtime rows at {TRAVEL_OT_RATE}, found %.', ot_rows;")
    add("  END IF;")
    add("")
    add(f"  RAISE NOTICE 'OK — {TARGET_CLIENT} has % rate rows; % Travel overtime rows set.', ms_rows, ot_rows;")
    add("END $$;")
    add("")
    add("COMMIT;")
    add("")
    return "\n".join(lines)


def print_summary() -> None:
    print("\nSprint 024 — Catalog amendments, decided without Dave (DRY RUN)")
    print("=" * 66)
    print(f"\n{DECIDED_BY}")
    print("\nWILL CHANGE:")
    print(f"  1. {TARGET_CLIENT} rate card seeded from {SOURCE_CLIENT} "
          f"(~{EXPECTED_VOLVO_ROWS} rows). Idempotent: skipped if it already has any.")
    print(f"  2. {TRAVEL_OT_ITEM} Right Seat Driver - Travel overtime = ${TRAVEL_OT_RATE} "
          f"on {', '.join(TRAVEL_OT_CLIENTS)}.")
    print("\nDELIBERATELY NOT GUESSED (needs an Intacct Item ID from accounting):")
    print("  - Chauffeur 'High Markets' second Item ID. Volvo bills chauffeur at 90,")
    print("    not 100, until issued. Maserati unaffected (both rates were 100).")
    print("  - EV Charging - Flat Rate and Per Diem - Flat Rate. Both stay as")
    print("    pass-throughs, billed on receipts at the client markup.")
    print("  - I00601's five-digit Item ID stays as DriveShop wrote it.")
    print("  Guessing an item ID puts a fake identifier on a real invoice; that is")
    print("  worse than the gap it closes.")
    print("\nNO WORK NEEDED (verified, not assumed):")
    print("  - The four 'Duplicate???' items are on ZERO rate cards already.")
    print("  - The 'In event estimate?' column is moot: the builder reads each")
    print("    client's rate card, so the 77 unpriced items never appear.")
    print("  - GL 4000.99 is referenced nowhere.")
    print("\nThis script never connects to the database. An operator applies the SQL.")


def main() -> int:
    parser = argparse.ArgumentParser(description="Apply Sprint 024 catalog amendments.")
    parser.add_argument("--confirm", action="store_true",
                        help="also write scripts/import_catalog_amendments.sql")
    args = parser.parse_args()

    print_summary()

    if not args.confirm:
        print(f"\nDry-run only. Re-run with --confirm to write "
              f"{OUTPUT_SQL_PATH.relative_to(PROJECT_ROOT)}.")
        return 0

    sql = generate_sql()
    OUTPUT_SQL_PATH.write_text(sql, encoding="utf-8")
    print(f"\nWrote {OUTPUT_SQL_PATH.relative_to(PROJECT_ROOT)} "
          f"({len(sql.splitlines())} lines).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
