#!/usr/bin/env python3
"""
Sprint 026 — Corporate cost on the rate cards.

Populates rate_card_items.corporate_cost so corporate-structure estimates stop
reporting ~100% gross profit.

Usage:
    python scripts/import_corporate_costs.py            # dry-run, prints only
    python scripts/import_corporate_costs.py --confirm  # also writes the .sql

An OPERATOR applies scripts/import_corporate_costs.sql via the Supabase SQL
editor. This script NEVER writes to the database.

--------------------------------------------------------------------------
THE RULE, AND WHERE IT CAME FROM

Dave's pricing workbook contained only prices (what the client pays). It had no
cost column, because cost is what DriveShop pays out internally and does not
belong on a client rate card. So corporate cost has never been loaded, and the
add paths recorded null for corporate estimates.

The rule below is recovered from the Sprint 016 cost rate card, which is still
in git at scripts/import_rate_cards.sql. That data was real DriveShop cost
data, and it is strikingly consistent — corporate cost was 50% of the unit rate
across every section:

    Planning & Administration Labor    66 of  66 rows at 0.50
    Onsite Event Labor                142 of 163 rows at 0.50
    Creative Costs                     11 of  11 rows at 0.50
    Logistics Expenses                249 of 392 rows at 0.50

The exceptions all sit at 1.00 — cost equals the rate — and they are
pass-throughs, which makes sense: DriveShop passes those through at cost and
earns only the client markup.

Confirmed by Ray, 2026-08-10.

  non-pass-through  -> corporate_cost = 50   (percent of unit_rate)
  pass-through      -> corporate_cost = 100  (percent of unit_rate; cost = rate)

Stored as a PERCENT (corporate_cost_is_percent = true) rather than a flat dollar
amount, so a later rate change carries the cost with it instead of silently
leaving a stale figure behind.

--------------------------------------------------------------------------
WHY THE OLD ROWS ARE NOT COPIED ACROSS ITEM BY ITEM

The Sprint 016 rate card used the pre-Sprint-019 item names ("Event Director
Day (10 hr)"); the current catalog uses DriveShop's own ("Event Director Days").
Matching one to the other is precisely the reconciliation Sprint 019 proved
impossible. The flat rule sidesteps it entirely and reproduces the same numbers
for ~85% of rows exactly.

--------------------------------------------------------------------------
WHAT THIS DOES NOT TOUCH

  - office_cost stays NULL. Office cost is DERIVED at estimate time from the
    client's office_payout_pct (the W8 fix). Writing a copy onto every rate card
    row would create that many places for it to drift out of sync with the
    client record. One source of truth, deliberately. A guard fails the load if
    any row has a stored office_cost.
  - No unit_rate, no overtime_rate, no fee_types, no estimate values.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_SQL_PATH = PROJECT_ROOT / "scripts" / "import_corporate_costs.sql"

DECIDED = "2026-08-10 Ray: confirmed 50% corporate cost, build it."

STANDARD_PCT = 50      # non-pass-through
PASS_THROUGH_PCT = 100  # cost == rate; DriveShop earns only the client markup

# Updated 2026-08-10 after the guard correctly rejected the first attempt.
# The original figures (1397 / 900 / 497) were written before Sprint 024 seeded
# Volvo MS's rate card from Volvo earlier the same day. That added Volvo's 69
# rows (45 pass-through + 24 standard) to a 21st client, so:
#     total        1397 + 69 = 1466
#     pass-through  900 + 45 =  945
#     standard      497 + 24 =  521
# The guard doing exactly what it was built for is the reason this was a clean
# rollback rather than a partial load. Keep the expectations hardcoded.
EXPECTED_TOTAL_ROWS = 1466
EXPECTED_PASS_THROUGH = 945
EXPECTED_STANDARD = 521


def generate_sql() -> str:
    lines: list[str] = []
    add = lines.append

    add("-- " + "=" * 75)
    add("-- Sprint 026 — Corporate cost on rate card items")
    add("-- Generated by scripts/import_corporate_costs.py — do not hand-edit.")
    add(f"-- {DECIDED}")
    add("--")
    add("-- Rule recovered from the Sprint 016 cost rate card (scripts/import_rate_cards.sql,")
    add("-- still in git): corporate cost was 50% of the unit rate across every section;")
    add("-- pass-throughs sat at 100% (cost == rate).")
    add("--")
    add("-- Stored as a PERCENT so a later rate change carries the cost with it.")
    add("-- office_cost is deliberately left NULL: office cost is derived from the")
    add("-- client's office_payout_pct at estimate time, and a stored copy would drift.")
    add("--")
    add("-- Safe to re-run. One transaction; if a guard fails, NOTHING is applied.")
    add("-- Touches rate_card_items.corporate_cost / corporate_cost_is_percent only.")
    add("-- " + "=" * 75)
    add("")
    add("BEGIN;")
    add("")
    add("-- Pass-through items: DriveShop's cost is the full rate.")
    add("UPDATE rate_card_items")
    add(f"   SET corporate_cost = {PASS_THROUGH_PCT},")
    add("       corporate_cost_is_percent = true")
    add(" WHERE is_pass_through = true;")
    add("")
    add("-- Everything else: half the rate.")
    add("UPDATE rate_card_items")
    add(f"   SET corporate_cost = {STANDARD_PCT},")
    add("       corporate_cost_is_percent = true")
    add(" WHERE is_pass_through = false;")
    add("")
    add("-- ---------------------------------------------------------------------")
    add("-- GUARD — verify before COMMIT.")
    add("-- ---------------------------------------------------------------------")
    add("DO $$")
    add("DECLARE total INT; pt INT; std INT; office_touched INT;")
    add("BEGIN")
    add("  SELECT count(*) INTO total FROM rate_card_items WHERE corporate_cost IS NOT NULL;")
    add(f"  SELECT count(*) INTO pt  FROM rate_card_items WHERE is_pass_through = true  AND corporate_cost = {PASS_THROUGH_PCT};")
    add(f"  SELECT count(*) INTO std FROM rate_card_items WHERE is_pass_through = false AND corporate_cost = {STANDARD_PCT};")
    add("  SELECT count(*) INTO office_touched FROM rate_card_items WHERE office_cost IS NOT NULL;")
    add("")
    add(f"  IF total <> {EXPECTED_TOTAL_ROWS} THEN")
    add(f"    RAISE EXCEPTION 'ABORT: % rows carry a corporate cost (expected %). Rate card row count has changed since planning.', total, {EXPECTED_TOTAL_ROWS};")
    add("  END IF;")
    add(f"  IF pt <> {EXPECTED_PASS_THROUGH} THEN")
    add(f"    RAISE EXCEPTION 'ABORT: % pass-through rows at {PASS_THROUGH_PCT}%% (expected %).', pt, {EXPECTED_PASS_THROUGH};")
    add("  END IF;")
    add(f"  IF std <> {EXPECTED_STANDARD} THEN")
    add(f"    RAISE EXCEPTION 'ABORT: % standard rows at {STANDARD_PCT}%% (expected %).', std, {EXPECTED_STANDARD};")
    add("  END IF;")
    add("  IF office_touched <> 0 THEN")
    add("    RAISE EXCEPTION 'ABORT: % rows have a stored office_cost. Office cost must stay derived from the client payout, not stored.', office_touched;")
    add("  END IF;")
    add("")
    add("  RAISE NOTICE 'OK — % rows costed (% pass-through at 100%%, % standard at 50%%); office_cost untouched.', total, pt, std;")
    add("END $$;")
    add("")
    add("COMMIT;")
    add("")
    return "\n".join(lines)


def print_summary() -> None:
    print("\nSprint 026 — Corporate cost on rate cards (DRY RUN)")
    print("=" * 64)
    print(f"\n{DECIDED}")
    print("\nRule (recovered from the Sprint 016 cost card, still in git):")
    print(f"  pass-through      corporate_cost = {PASS_THROUGH_PCT}%  (cost == rate; margin is the client markup)")
    print(f"  everything else   corporate_cost = {STANDARD_PCT}%  (matched ~85% of the old rows exactly)")
    print("\nExpected after apply:")
    print(f"  {EXPECTED_PASS_THROUGH:>5} pass-through rows at {PASS_THROUGH_PCT}%")
    print(f"  {EXPECTED_STANDARD:>5} standard rows at {STANDARD_PCT}%")
    print(f"  {EXPECTED_TOTAL_ROWS:>5} total costed")
    print("\nDeliberately NOT touched:")
    print("  office_cost stays NULL — office cost is derived from the client's")
    print("  office_payout_pct at estimate time. A stored copy on 1,397 rows would")
    print("  be 1,397 chances to drift. The guard fails if any row has one.")
    print("\nThis script never connects to the database. An operator applies the SQL.")


def main() -> int:
    parser = argparse.ArgumentParser(description="Populate corporate cost on rate card items.")
    parser.add_argument("--confirm", action="store_true",
                        help="also write scripts/import_corporate_costs.sql")
    args = parser.parse_args()

    print_summary()

    if not args.confirm:
        print(f"\nDry-run only. Re-run with --confirm to write "
              f"{OUTPUT_SQL_PATH.relative_to(PROJECT_ROOT)}.")
        return 0

    OUTPUT_SQL_PATH.write_text(generate_sql(), encoding="utf-8")
    print(f"\nWrote {OUTPUT_SQL_PATH.relative_to(PROJECT_ROOT)}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
