-- ===========================================================================
-- Sprint 023 — Client AR payment terms
-- Generated by scripts/import_client_payment_terms.py — do not hand-edit.
-- Source: Tatiana, 'Customers with Pmt Terms.xlsx', 2026-08-10
--
-- Safe to re-run. One transaction: if the guard fails, NOTHING is applied.
-- Touches the `clients` table only. No schema change.
-- ===========================================================================

BEGIN;

-- 21 guarded updates, keyed on name.
-- `No Client` is deliberately absent and stays NULL.
UPDATE clients SET default_payment_terms = 'Net 30' WHERE lower(name) = lower('Acura');
UPDATE clients SET default_payment_terms = 'Net 60' WHERE lower(name) = lower('Audi');
UPDATE clients SET default_payment_terms = 'Net 60' WHERE lower(name) = lower('Bentley');
UPDATE clients SET default_payment_terms = 'Net 30' WHERE lower(name) = lower('Ferrari');
UPDATE clients SET default_payment_terms = 'Net 30' WHERE lower(name) = lower('Genesis');
UPDATE clients SET default_payment_terms = 'Net 30' WHERE lower(name) = lower('Hankook');
UPDATE clients SET default_payment_terms = 'Net 30' WHERE lower(name) = lower('Honda');
UPDATE clients SET default_payment_terms = 'Net 30' WHERE lower(name) = lower('Hyundai');
UPDATE clients SET default_payment_terms = 'Net 30' WHERE lower(name) = lower('JLR');
UPDATE clients SET default_payment_terms = 'Net 60' WHERE lower(name) = lower('Lamborghini');
UPDATE clients SET default_payment_terms = 'Net 45' WHERE lower(name) = lower('Lexus');
UPDATE clients SET default_payment_terms = 'Net 45' WHERE lower(name) = lower('Lucid');
UPDATE clients SET default_payment_terms = 'Net 30' WHERE lower(name) = lower('MB');
UPDATE clients SET default_payment_terms = 'Net 60' WHERE lower(name) = lower('Maserati');
UPDATE clients SET default_payment_terms = 'Net 30' WHERE lower(name) = lower('Mazda');
UPDATE clients SET default_payment_terms = 'Net 45' WHERE lower(name) = lower('Polestar');
UPDATE clients SET default_payment_terms = 'Net 30' WHERE lower(name) = lower('Porsche');
UPDATE clients SET default_payment_terms = 'Net 45' WHERE lower(name) = lower('Toyota');
UPDATE clients SET default_payment_terms = 'Net 60' WHERE lower(name) = lower('VW');
UPDATE clients SET default_payment_terms = 'Net 45' WHERE lower(name) = lower('Volvo');
UPDATE clients SET default_payment_terms = 'Net 45' WHERE lower(name) = lower('Volvo MS');

-- ---------------------------------------------------------------------
-- GUARD — verify before COMMIT. A client name that does not match the
-- database would leave its UPDATE affecting zero rows, silently. This is
-- the only realistic failure mode for a guarded update keyed on name.
-- ---------------------------------------------------------------------
DO $$
DECLARE n INT;
BEGIN
  SELECT count(*) INTO n FROM clients WHERE default_payment_terms IS NOT NULL;
  IF n <> 21 THEN
    RAISE EXCEPTION 'ABORT: % clients carry payment terms (expected %). A client name in the mapping probably does not match the database.', n, 21;
  END IF;
  RAISE NOTICE 'OK — % clients carry AR payment terms.', n;
END $$;

COMMIT;
