-- ===========================================================================
-- Sprint 024 — Catalog amendments (decided without Dave)
-- Generated by scripts/import_catalog_amendments.py — do not hand-edit.
-- 2026-08-10 Ray: proceed on best-guess, do not wait for Dave.
--
-- Safe to re-run. One transaction: if a guard fails, NOTHING is applied.
-- Touches rate_card_items only. No schema change, no fee_types change.
-- ===========================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- 1. Seed Volvo MS's rate card from Volvo.
--    The NOT EXISTS makes this idempotent: on a re-run the target
--    already has rows and nothing is inserted, so rates edited later
--    are never overwritten by a second apply.
-- ---------------------------------------------------------------------
INSERT INTO rate_card_items (
  client_id, section_id, name, unit_rate, unit_label, gl_code,
  is_pass_through, has_overtime_rate, overtime_rate,
  notes, fee_type_id, display_order, is_active, is_rate_locked
)
SELECT (SELECT id FROM clients WHERE lower(name) = lower('Volvo MS')),
       r.section_id, r.name, r.unit_rate, r.unit_label, r.gl_code,
       r.is_pass_through, r.has_overtime_rate, r.overtime_rate,
       r.notes, r.fee_type_id, r.display_order, r.is_active, r.is_rate_locked
  FROM rate_card_items r
 WHERE r.client_id = (SELECT id FROM clients WHERE lower(name) = lower('Volvo'))
   AND NOT EXISTS (
         SELECT 1 FROM rate_card_items x
          WHERE x.client_id = (SELECT id FROM clients WHERE lower(name) = lower('Volvo MS'))
       );

-- ---------------------------------------------------------------------
-- 2. I0124 Right Seat Driver - Travel: set the $80 overtime rate
--    Dave implied on Lucid and MB but left off the parent row.
-- ---------------------------------------------------------------------
UPDATE rate_card_items
   SET has_overtime_rate = true,
       overtime_rate = 80
 WHERE fee_type_id = (SELECT id FROM fee_types WHERE intacct_ar_item_id = 'I0124')
   AND client_id IN (SELECT id FROM clients WHERE name IN ('Lucid', 'MB'));

-- ---------------------------------------------------------------------
-- GUARD — verify before COMMIT.
-- ---------------------------------------------------------------------
DO $$
DECLARE ms_rows INT; src_rows INT; ot_rows INT;
BEGIN
  SELECT count(*) INTO ms_rows FROM rate_card_items r JOIN clients c ON c.id = r.client_id
   WHERE lower(c.name) = lower('Volvo MS');
  SELECT count(*) INTO src_rows FROM rate_card_items r JOIN clients c ON c.id = r.client_id
   WHERE lower(c.name) = lower('Volvo');

  IF ms_rows <> src_rows THEN
    RAISE EXCEPTION 'ABORT: Volvo MS has % rate rows but Volvo has % — the copy did not land cleanly.', ms_rows, src_rows;
  END IF;

  SELECT count(*) INTO ot_rows FROM rate_card_items r
    JOIN clients c ON c.id = r.client_id
   WHERE r.fee_type_id = (SELECT id FROM fee_types WHERE intacct_ar_item_id = 'I0124')
     AND c.name IN ('Lucid', 'MB')
     AND r.overtime_rate = 80;
  IF ot_rows <> 2 THEN
    RAISE EXCEPTION 'ABORT: expected 2 Travel overtime rows at 80, found %.', ot_rows;
  END IF;

  RAISE NOTICE 'OK — Volvo MS has % rate rows; % Travel overtime rows set.', ms_rows, ot_rows;
END $$;

COMMIT;
