#!/usr/bin/env python3
"""
Sprint 022 — Client Accounting Identity + VW Merge.

Sets clients.intacct_customer_id from the mapping Tatiana confirmed, and
collapses the duplicate VW / Volkswagen client records into one.

Usage:
    python scripts/import_client_accounting.py            # dry-run, prints only
    python scripts/import_client_accounting.py --confirm  # also writes the .sql

Then an OPERATOR reviews and applies scripts/import_client_accounting.sql via
the Supabase SQL editor. This script NEVER writes to the database — it has no
database client imported and opens no connection.

Provenance of the mapping (do not re-derive it):
  Tatiana sent `Customers 8.10.26.xlsx` (296 customers) on 2026-08-10, then
  confirmed every remaining decision by email the same day. The table below is
  those confirmations transcribed literally. There is no name matching, no
  fuzzy matching and no spreadsheet parsing in this script by design: Sprint 019
  proved that inferring Intacct identity from names or GL codes produces wrong
  answers. Full provenance in planning/QUESTIONS.md.

Two customer IDs are intentionally shared by two clients each:
  C0004 -> Acura AND Honda      ("Acura/Honda" is one Intacct account)
  C0099 -> Volvo AND Volvo MS   (Volvo MS is a program under the Volvo client)
Any future uniqueness validation must permit this.

The VW merge, and why the order matters (verified against the live DB,
Stage A audit 2026-08-10):
  - `Volkswagen` holds 70 rate_card_items and office_payout_pct 0.7500.
  - `VW`         holds  0 rate_card_items and office_payout_pct 0.8000.
  - Neither has estimates or contacts.
  - clients.name AND clients.code are both UNIQUE.
  - rate_card_items.client_id is ON DELETE **CASCADE** (confirmed live), so
    deleting the wrong record would silently destroy its whole rate card with
    no error. The generated SQL therefore guards the delete explicitly rather
    than trusting the database to refuse it.
  So: carry the 0.8000 payout across FIRST, then delete the empty `VW` row
  (which frees both the name and the code), then rename `Volkswagen` to `VW`.
  Renaming first would collide on the unique name/code.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_SQL_PATH = PROJECT_ROOT / "scripts" / "import_client_accounting.sql"

OPERATOR_DECISIONS_APPLIED = (
    "2026-08-10 Tatiana: full customer mapping confirmed; VW and Volkswagen "
    "collapse to one client named VW on C0208; Volvo MS shares Volvo's C0099."
)

# Client name -> Intacct customer ID. Literal, confirmed, not derived.
# `No Client` is deliberately absent: it is our internal fallback, not a
# DriveShop account, and must stay NULL.
CUSTOMER_IDS: dict[str, str] = {
    "Acura":       "C0004",   # shared with Honda, intended
    "Audi":        "C0009",
    "Bentley":     "C0091",
    "Ferrari":     "C0202",
    "Genesis":     "C0121",   # already set in Sprint 019, re-asserted
    "Hankook":     "C0255",
    "Honda":       "C0004",   # shared with Acura, intended
    "Hyundai":     "C0019",   # already set in Sprint 019, re-asserted
    "JLR":         "C0026",
    "Lamborghini": "C0156",   # already set in Sprint 019, re-asserted
    "Lexus":       "C0134",   # Team One Lexus: bills through the agency
    "Lucid":       "C0294",
    "Maserati":    "C0028",   # already set in Sprint 019, re-asserted
    "Mazda":       "C0029",   # already set in Sprint 019, re-asserted
    "MB":          "C0032",
    "Polestar":    "C0207",
    "Porsche":     "C0041",
    "Toyota":      "C0048",   # already set in Sprint 019, re-asserted
    "Volvo":       "C0099",   # shared with Volvo MS, intended
    "Volvo MS":    "C0099",   # shared with Volvo, intended
}

# Handled inside the merge block instead of the loop above, because the row
# only takes this name at the end of the merge.
MERGED_VW_NAME = "VW"
MERGED_VW_CODE = "VW"
MERGED_VW_CUSTOMER_ID = "C0208"

# Observed in the Stage A audit. Used only to assert the world still looks the
# way it did when this was planned; the SQL re-checks these live and aborts the
# whole transaction if they have changed.
EXPECTED_VOLKSWAGEN_RATE_ROWS = 70
EXPECTED_VW_RATE_ROWS = 0
EXPECTED_VW_PAYOUT = "0.8000"
EXPECTED_CLIENTS_WITH_CUSTOMER_ID_AFTER = 21


def sql_str(s: str) -> str:
    """Single-quote a value for SQL, escaping embedded quotes."""
    return "'" + str(s).replace("'", "''") + "'"


def generate_sql() -> str:
    lines: list[str] = []
    add = lines.append

    add("-- " + "=" * 75)
    add("-- Sprint 022 — Client Accounting Identity + VW Merge")
    add("-- Generated by scripts/import_client_accounting.py — do not hand-edit.")
    add(f"-- Operator decisions: {OPERATOR_DECISIONS_APPLIED}")
    add("--")
    add("-- Safe to re-run. Every statement is idempotent and the whole file is one")
    add("-- transaction: if any guard fails, NOTHING is applied.")
    add("--")
    add("-- Touches the `clients` table only. No schema change. No estimate value")
    add("-- changes. fee_types and rate_card_items are never written.")
    add("-- " + "=" * 75)
    add("")
    add("BEGIN;")
    add("")

    # ---- Guard 1: the merge preconditions -----------------------------------
    add("-- ---------------------------------------------------------------------")
    add("-- GUARD 1 — refuse to proceed unless the two VW records look as audited.")
    add("--")
    add("-- rate_card_items.client_id is ON DELETE CASCADE, so deleting the wrong")
    add("-- record destroys its rate card silently. This guard is the only thing")
    add("-- standing between a mistake and 70 lost prices. Do not remove it.")
    add("-- ---------------------------------------------------------------------")
    add("DO $$")
    add("DECLARE")
    add("  vw_rows   INT;")
    add("  vk_rows   INT;")
    add("  vw_count  INT;")
    add("  vk_count  INT;")
    add("BEGIN")
    add("  SELECT count(*) INTO vw_count FROM clients WHERE lower(name) = 'vw';")
    add("  SELECT count(*) INTO vk_count FROM clients WHERE lower(name) = 'volkswagen';")
    add("")
    add("  IF vw_count = 1 AND vk_count = 1 THEN")
    add("    SELECT count(*) INTO vw_rows FROM rate_card_items r")
    add("      JOIN clients c ON c.id = r.client_id WHERE lower(c.name) = 'vw';")
    add("    SELECT count(*) INTO vk_rows FROM rate_card_items r")
    add("      JOIN clients c ON c.id = r.client_id WHERE lower(c.name) = 'volkswagen';")
    add("")
    add(f"    IF vw_rows <> {EXPECTED_VW_RATE_ROWS} THEN")
    add("      RAISE EXCEPTION 'ABORT: the VW record holds % rate card rows (expected 0). "
        "Deleting it would destroy them. Re-run the Stage A audit and re-plan.', vw_rows;")
    add("    END IF;")
    add("")
    add("    IF vk_rows = 0 THEN")
    add("      RAISE EXCEPTION 'ABORT: the Volkswagen record holds 0 rate card rows "
        "(expected %). The wrong record would survive the merge.', "
        f"{EXPECTED_VOLKSWAGEN_RATE_ROWS};")
    add("    END IF;")
    add("")
    add("  ELSIF vw_count = 1 AND vk_count = 0 THEN")
    add("    RAISE NOTICE 'Merge already applied (VW exists, Volkswagen does not). "
        "Skipping merge, applying customer IDs only.';")
    add("  ELSE")
    add("    RAISE EXCEPTION 'ABORT: unexpected client state — % row(s) named VW, "
        "% named Volkswagen.', vw_count, vk_count;")
    add("  END IF;")
    add("END $$;")
    add("")

    # ---- The merge ----------------------------------------------------------
    add("-- ---------------------------------------------------------------------")
    add("-- MERGE — order is mandatory.")
    add("--   1. carry VW's non-standard office payout onto Volkswagen")
    add("--   2. delete the empty VW row (frees the UNIQUE name AND code)")
    add("--   3. rename Volkswagen to VW and give it the code + customer ID")
    add("-- Renaming before deleting collides on clients.name / clients.code.")
    add("-- ---------------------------------------------------------------------")
    add("")
    add("-- 1. Carry the payout across. Read live rather than hardcoded, so the")
    add("--    real value moves even if it changed since the audit. Only fires when")
    add("--    both rows still exist, which makes this safe to re-run.")
    add("UPDATE clients SET office_payout_pct = (")
    add("         SELECT office_payout_pct FROM clients WHERE lower(name) = 'vw'")
    add("       )")
    add(" WHERE lower(name) = 'volkswagen'")
    add("   AND EXISTS (SELECT 1 FROM clients WHERE lower(name) = 'vw');")
    add("")
    add("-- 2. Delete the empty VW record. Guard 1 has proven it holds no rates.")
    add("DELETE FROM clients")
    add(" WHERE lower(name) = 'vw'")
    add("   AND NOT EXISTS (")
    add("         SELECT 1 FROM rate_card_items r")
    add("          JOIN clients c ON c.id = r.client_id")
    add("         WHERE lower(c.name) = 'vw'")
    add("       );")
    add("")
    add("-- 3. Rename Volkswagen and take over the identity.")
    add("UPDATE clients")
    add(f"   SET name = {sql_str(MERGED_VW_NAME)},")
    add(f"       code = {sql_str(MERGED_VW_CODE)},")
    add(f"       intacct_customer_id = {sql_str(MERGED_VW_CUSTOMER_ID)}")
    add(" WHERE lower(name) = 'volkswagen';")
    add("")

    # ---- Customer IDs -------------------------------------------------------
    add("-- ---------------------------------------------------------------------")
    add(f"-- CUSTOMER IDS — {len(CUSTOMER_IDS)} guarded updates, keyed on name.")
    add("-- `No Client` is deliberately absent and stays NULL.")
    add("-- ---------------------------------------------------------------------")
    for name in sorted(CUSTOMER_IDS):
        cid = CUSTOMER_IDS[name]
        add(
            f"UPDATE clients SET intacct_customer_id = {sql_str(cid)} "
            f"WHERE lower(name) = lower({sql_str(name)});"
        )
    add("")

    # ---- Guard 2: verify the outcome before committing ----------------------
    add("-- ---------------------------------------------------------------------")
    add("-- GUARD 2 — verify the result before COMMIT. Any failure rolls back the")
    add("-- entire file, leaving the database exactly as it was.")
    add("-- ---------------------------------------------------------------------")
    add("DO $$")
    add("DECLARE")
    add("  vw_n      INT;")
    add("  vk_n      INT;")
    add("  vw_rates  INT;")
    add("  vw_payout NUMERIC;")
    add("  with_id   INT;")
    add("BEGIN")
    add("  SELECT count(*) INTO vw_n FROM clients WHERE name = 'VW';")
    add("  SELECT count(*) INTO vk_n FROM clients WHERE lower(name) = 'volkswagen';")
    add("  IF vw_n <> 1 OR vk_n <> 0 THEN")
    add("    RAISE EXCEPTION 'ABORT: after merge expected exactly 1 VW and 0 Volkswagen, "
        "found % and %.', vw_n, vk_n;")
    add("  END IF;")
    add("")
    add("  SELECT count(*) INTO vw_rates FROM rate_card_items r")
    add("    JOIN clients c ON c.id = r.client_id WHERE c.name = 'VW';")
    add(f"  IF vw_rates <> {EXPECTED_VOLKSWAGEN_RATE_ROWS} THEN")
    add("    RAISE EXCEPTION 'ABORT: merged VW holds % rate card rows (expected %). "
        f"The wrong record survived.', vw_rates, {EXPECTED_VOLKSWAGEN_RATE_ROWS};")
    add("  END IF;")
    add("")
    add("  SELECT office_payout_pct INTO vw_payout FROM clients WHERE name = 'VW';")
    add(f"  IF vw_payout <> {EXPECTED_VW_PAYOUT} THEN")
    add("    RAISE EXCEPTION 'ABORT: merged VW office_payout_pct is % (expected %). "
        "The non-standard payout was lost; every future VW estimate would be "
        f"mispriced.', vw_payout, {EXPECTED_VW_PAYOUT};")
    add("  END IF;")
    add("")
    add("  SELECT count(*) INTO with_id FROM clients WHERE intacct_customer_id IS NOT NULL;")
    add(f"  IF with_id <> {EXPECTED_CLIENTS_WITH_CUSTOMER_ID_AFTER} THEN")
    add("    RAISE EXCEPTION 'ABORT: % clients carry a customer ID (expected %). "
        "A client name in the mapping probably does not match the database.', "
        f"with_id, {EXPECTED_CLIENTS_WITH_CUSTOMER_ID_AFTER};")
    add("  END IF;")
    add("")
    add("  RAISE NOTICE 'OK — 1 VW with % rates at payout %, % clients carry a "
        "customer ID.', vw_rates, vw_payout, with_id;")
    add("END $$;")
    add("")
    add("COMMIT;")
    add("")
    return "\n".join(lines)


def print_summary() -> None:
    shared: dict[str, list[str]] = {}
    for name, cid in CUSTOMER_IDS.items():
        shared.setdefault(cid, []).append(name)
    shared[MERGED_VW_CUSTOMER_ID] = [f"{MERGED_VW_NAME} (merged)"]

    print("\nSprint 022 — Client Accounting Identity + VW Merge (DRY RUN)")
    print("=" * 66)
    print(f"\nOperator decisions applied:\n  {OPERATOR_DECISIONS_APPLIED}")

    print(f"\nCustomer IDs to assign: {len(CUSTOMER_IDS) + 1} clients")
    for cid in sorted(shared):
        names = ", ".join(sorted(shared[cid]))
        flag = "   <-- SHARED, intended" if len(shared[cid]) > 1 else ""
        print(f"  {cid}  {names}{flag}")
    print("  (none)  No Client — internal fallback, deliberately left NULL")

    print("\nVW merge sequence:")
    print(f"  1. carry office_payout_pct {EXPECTED_VW_PAYOUT} from 'VW' onto 'Volkswagen'")
    print(f"  2. delete the empty 'VW' row  (audited at {EXPECTED_VW_RATE_ROWS} rate card rows)")
    print(f"  3. rename 'Volkswagen' -> 'VW', code 'VW', customer {MERGED_VW_CUSTOMER_ID}")
    print(f"     ('Volkswagen' audited at {EXPECTED_VOLKSWAGEN_RATE_ROWS} rate card rows, "
          "which must survive)")

    print("\nGuards in the generated SQL (all inside one transaction):")
    print("  GUARD 1  aborts unless VW has 0 rate rows and Volkswagen has some.")
    print("           rate_card_items.client_id is ON DELETE CASCADE — without this")
    print("           guard a wrong delete destroys the rate card silently.")
    print("  GUARD 2  aborts unless, after the merge: exactly 1 VW, 0 Volkswagen,")
    print(f"           {EXPECTED_VOLKSWAGEN_RATE_ROWS} rate rows on VW, payout "
          f"{EXPECTED_VW_PAYOUT}, and {EXPECTED_CLIENTS_WITH_CUSTOMER_ID_AFTER} clients with an ID.")
    print("\nThis script never connects to the database. An operator applies the SQL.")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Assign Intacct customer IDs and merge the duplicate VW client."
    )
    parser.add_argument(
        "--confirm", action="store_true",
        help="also write scripts/import_client_accounting.sql",
    )
    args = parser.parse_args()

    print_summary()

    if not args.confirm:
        print(f"\nDry-run only. Re-run with --confirm to write "
              f"{OUTPUT_SQL_PATH.relative_to(PROJECT_ROOT)}.")
        return 0

    sql = generate_sql()
    OUTPUT_SQL_PATH.write_text(sql, encoding="utf-8")
    print(f"\nWrote {OUTPUT_SQL_PATH.relative_to(PROJECT_ROOT)} "
          f"({len(sql.splitlines())} lines).")
    print("Review it, then apply via the Supabase SQL editor.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
